### ISSUE TITLE
Implement AFK notifier. 

### ISSUE THREAD

**Issue by benrobson8** [benrobson8/zander#44]

**Comment by jasoryeh** [comment]
Is this an in-game feature? As in the player stops playing, or Discord goes to an idle state?

**Comment by shadowolfyt** [comment]
In-game feature. When the player stops moving for an amount of minute indicated by the config file, it broadcasts a message stating that the user is afk and changes their name colour in the tab to gray.

**Comment by shadowolfyt** [comment]
Ensure there is a "afktimeout" option in the config.yml
