### ISSUE TITLE
Create a sign in and authentication system.

### ISSUE THREAD

**Issue by benrobson8** [benrobson8/zander#72]

**Comment by jasoryeh** [comment]
Please elaborate? I'm not sure what you mean by a sign in system...

**Comment by shadowolfyt** [comment]
Basically when a player links their discord account they then have the ability to change and manage their profile, but I need some form of system to allow authentication and sign in, I thought by using discord to link it should be used to login?

**Comment by shadowolfyt** [comment]
IDEA: Ideally, use the players Discord account to connect and verify. Since they are mainly on Discord, ideally that is how I'd like to go, if that's possible.
